# 01 - Preprocesamiento de datos

Carga el dataset crudo (Fake.csv / True.csv), lo limpia y genera el dataset procesado usado por el notebook de Machine Learning.

In [1]:
import sys
sys.path.append('../src')

from fake_news_mle.preprocessing import load_raw_data, build_features, preprocess

## Cargar datos crudos

In [2]:
df_raw = load_raw_data(raw_dir='../data/raw')
df_raw.head()

,title,text,subject,date,label
0,Ben Stein Calls Out 9th Circuit Court: Committ...,"21st Century Wire says Ben Stein, reputable pr...",US_News,"February 13, 2017",0
1,Trump drops Steve Bannon from National Securit...,WASHINGTON (Reuters) - U.S. President Donald T...,politicsNews,"April 5, 2017",1
2,Puerto Rico expects U.S. to lift Jones Act shi...,(Reuters) - Puerto Rico Governor Ricardo Rosse...,politicsNews,"September 27, 2017",1
3,OOPS: Trump Just Accidentally Confirmed He Le...,"On Monday, Donald Trump once again embarrassed...",News,"May 22, 2017",0
4,Donald Trump heads for Scotland to reopen a go...,"GLASGOW, Scotland (Reuters) - Most U.S. presid...",politicsNews,"June 24, 2016",1

## Conteos

In [3]:
print(df_raw['label'].value_counts())
print(df_raw['subject'].value_counts())

label
0    23481
1    21417
Name: count, dtype: int64
subject
politicsNews       11272
worldnews          10145
News                9050
politics            6841
left-news           4459
Government News     1570
US_News              783
Middle-east          778
Name: count, dtype: int64

## Construir features y limpiar texto

In [4]:
df_features = build_features(df_raw)
df_features.head()

,title,subject,date,clean_text,text_length,label
0,Ben Stein Calls Out 9th Circuit Court: Committ...,US_News,"February 13, 2017",ben stein calls out th circuit court committed...,184,0
1,Trump drops Steve Bannon from National Securit...,politicsNews,"April 5, 2017",trump drops steve bannon from national securit...,775,1
2,Puerto Rico expects U.S. to lift Jones Act shi...,politicsNews,"September 27, 2017",puerto rico expects us to lift jones act shipp...,313,1
3,OOPS: Trump Just Accidentally Confirmed He Le...,News,"May 22, 2017",oops trump just accidentally confirmed he leak...,192,0
4,Donald Trump heads for Scotland to reopen a go...,politicsNews,"June 24, 2016",donald trump heads for scotland to reopen a go...,529,1

## Guardar dataset procesado

In [5]:
df_final = preprocess(raw_dir='../data/raw', processed_dir='../data/processed')
df_final.shape

Dataset procesado guardado en: ..\data\processed\news_processed.parquet (44898 filas)

(44898, 6)